# Generated by Django 5.2.8 on 2026-03-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название сети')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='social_media_icons/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
                'ordering': ['name'],
            },
        ),
    ]
